<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        authcek();
        admincek();
    }

    function index()
    {
        $data['karyawan'] = $this->db->get('tbl_karyawan')->num_rows();
        $data['mhs'] = $this->db->get('tbl_mhs_magang')->num_rows();
        $data['magang'] = $this->db->get('tbl_magang')->num_rows();
        $data['pending'] = $this->db->get_where('tbl_mhs_magang', array('status' => 'p'))->num_rows();
        $data['aktif'] = $this->db->get_where('tbl_users', array('active' => 't'))->num_rows();
        $data['_view'] = 'dashboard';
        $data['tittle'] = 'Dashboard';
        $this->load->view('layouts/main', $data);
    }
}
