<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bagian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bagian by id_bagian
     */
    function get_bagian($id_bagian)
    {
        return $this->db->get_where('tbl_bagian',array('id_bagian'=>$id_bagian))->row_array();
    }
        
    /*
     * Get all tbl_bagian
     */
    function get_all_tbl_bagian()
    {
        $this->db->order_by('id_bagian', 'desc');
        return $this->db->get('tbl_bagian')->result_array();
    }
        
    /*
     * function to add new bagian
     */
    function add_bagian($params)
    {
        $this->db->insert('tbl_bagian',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bagian
     */
    function update_bagian($id_bagian,$params)
    {
        $this->db->where('id_bagian',$id_bagian);
        return $this->db->update('tbl_bagian',$params);
    }
    
    /*
     * function to delete bagian
     */
    function delete_bagian($id_bagian)
    {
        return $this->db->delete('tbl_bagian',array('id_bagian'=>$id_bagian));
    }
}
