<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Karyawan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get karyawan by id_karyawan
     */
    function get_karyawan($id_karyawan)
    {
        return $this->db->get_where('tbl_karyawan', array('id_karyawan' => $id_karyawan))->row_array();
    }
    function get_karyawan_user($email)
    {

        $this->db->select('*');
        $this->db->from('tbl_karyawan');
        $this->db->join('tbl_users', 'tbl_karyawan.id_user = tbl_users.id_user');
        $this->db->where('tbl_users.email', $email);
        return $this->db->get()->row_array();
    }

    /*
     * Get all tbl_karyawan
     */
    function get_all_tbl_karyawan()
    {
        $this->db->order_by('id_karyawan', 'desc');
        return $this->db->get('tbl_karyawan')->result_array();
    }

    /*
     * function to add new karyawan
     */
    function add_karyawan($params)
    {
        $this->db->insert('tbl_karyawan', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update karyawan
     */
    function update_karyawan($id_karyawan, $params)
    {
        $this->db->where('id_karyawan', $id_karyawan);
        return $this->db->update('tbl_karyawan', $params);
    }

    /*
     * function to delete karyawan
     */
    function delete_karyawan($id_karyawan)
    {
        return $this->db->delete('tbl_karyawan', array('id_karyawan' => $id_karyawan));
    }
}
